### ISSUE TITLE
open apps drawer on tv

### ISSUE THREAD

**Issue by ghost** [louis49/androidtv-remote#14]
hi, 

I'm trying to figure out how to open the apps drawer on the tv.
what keycode should it be?
because I tried 284 (KEYCODE_ALL_APPS) and it didn't work
It is the behavior of pressing the 9-dot button on the remote.

![image](https://user-images.githubusercontent.com/77443498/156388320-bfcfacf5-c654-400f-9e46-344be5311dc7.png)

**Comment by louis49** [comment]
I think it's KEYCODE_HOME

**Comment by techie-gabbar** [comment]
@Ganime422 R u able to make remote 
Android to Android TV
IOS to Android TV
