### ISSUE TITLE
Android TV Message Send Help 

### ISSUE THREAD

**Issue by piyush2greedy** [louis49/androidtv-remote#16]
@louis49 
I have been able to do a successful SSL Handshake from Android to Android TV. Next thing is that I need to send message via SSL Socket. 

Can anyone help me in that?
In NodeJS Version it is done through proto. 
How to do it in Android. Can u share some insights.

**Comment by louis49** [comment]
Hi
Protobuf is also available for Android with Java and Kotlin : https://developers.google.com/protocol-buffers/docs/kotlintutorial

**Comment by piyush2greedy** [comment]
Thanks, @louis49. Let me give it a try. Will do in similar way in Android how u did it in NodejS..
