### ISSUE TITLE
Open application by package name

### ISSUE THREAD

**Issue by sonic16x** [louis49/androidtv-remote#17]
Hi, how I can open application by package name?

**Comment by piyush2greedy** [comment]
@sonic16x Do u need to open it from NodeJS or Java Code

**Comment by sonic16x** [comment]
@piyush2greedy from NodeJs, for example package name of app 'com.ololo'

**Comment by piyush2greedy** [comment]
@sonic16x 
You can try calling 

this.remoteManager.sendAppLink(app_link)

*app_link - try sending 
https://www.netflix.com/ - Will open Netflix

Similar for other apps

**Comment by louis49** [comment]
for the moment only a deep link allows to launch an app - this is not possible with the name of the package without ADB
