### ISSUE TITLE
What version of Android Tv does this work with?

### ISSUE THREAD

**Issue by zerbzman** [louis49/androidtv-remote#19]
Hey, 

What versions of Android TV does this support? I factory restored my tv and now this doesn't work :(

**Comment by louis49** [comment]
Android 11

**Comment by zerbzman** [comment]
Thanks, I wish I could tell what Android version the TV got set to. It used to work but now it doesn't. This is what the example script shows now. 
`Start Pairing Connect`
`Error: connect ETIMEDOUT 10.3.0.68:6467
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.3.0.68',
  port: 6467
}
`

**Comment by zerbzman** [comment]
This ended up resolving itself and my TV auto updated to the newest interface. Everything works again.

**Comment by RehmanAli34** [comment]
Hi @zerbzman, @louis49 

I have a swift code to control android tv version 2. If I share my project can you please run it on your tv and tell me whether it is working or not. I have currently not a smart tv to test it. Its a silly comment sorry for that. But I would be thankful if you help me.
