### ISSUE TITLE
SEND KEY

### ISSUE THREAD

**Issue by piyush2greedy** [louis49/androidtv-remote#2]
@louis49 
How to send UP DOWN LEFT RIGHTS in sendKey. Can u please tell.
androidRemote.sendKey(RemoteKeyCode.UP, RemoteDirection.SHORT) is not workinng

**Comment by louis49** [comment]
androidRemote.sendKey(RemoteKeyCode.KEYCODE_DPAD_UP, RemoteDirection.SHORT)
