### ISSUE TITLE
Connection times out on tv shutoff

### ISSUE THREAD

**Issue by zerbzman** [louis49/androidtv-remote#20]
Hey,

Is there something I'm missing or something I need to turn on so the connection doesn't close and time out when I turn off the TV.  I'm not able to turn on the TV via this protocol.

**Comment by piyush2greedy** [comment]
@zerbzman what is code u r using nodejs or android.

**Comment by zerbzman** [comment]
node

**Comment by louis49** [comment]
You need to turn off deep sleep on your androidtv settings

**Comment by zerbzman** [comment]
I have tried to using Wakelock but that doesn't seem to work anymore. Do you know of a way to prevent deep sleep?

**Comment by louis49** [comment]
It's in AndroidTV parameters - it could be different between devices

**Comment by zerbzman** [comment]
Ok, I found an option that wakes the TV periodically to look for casting devices. 

The tv will connect to my app and authenticate but the power on command doesn't work. I have tried sending it right after authentication but it doesn't work. Any thoughts?

**Comment by zerbzman** [comment]
OK! Here is what worked for me.

1. Make sure that Networked Standby is turned on in the settings
- Go to Settings -> Network & Internet -> Networked Standby
2. Turn ON the TV by sending 1 Wake On Lan packet and then another at least 3 seconds after.

I have to do more testing to see if this still works to turn on the TV a day later.
