### ISSUE TITLE
Setup Help - Hostname

### ISSUE THREAD

**Issue by pptyasar** [louis49/androidtv-remote#22]
Can anyone help me on  How to get "hostname" & Cert, Basically I need to know how to pair

**Comment by louis49** [comment]
Cert is generated if you don't create it

hostname is the name of your device on local network 

You can inspirate your code with mine : https://github.com/louis49/homebridge-plugin-androidtv

**Comment by pptyasar** [comment]
Thanks @louis49 , How to run this repo(andrdoitv-remote) in angular or expressjs, Sorry i am noob

**Comment by louis49** [comment]
It's a server side module : It will not work

**Comment by pptyasar** [comment]
So  it can run on nodejs/expressjs right
