### ISSUE TITLE
Running issue with React-Native

### ISSUE THREAD

**Issue by piyush2greedy** [louis49/androidtv-remote#3]
@louis49 
Thanks for the help. Can u help how to make it run in react-native.
It throws node-forge (unable to resolve module) error in react-native.

Can u help how to make it work in react-native

**Comment by louis49** [comment]
It’s a server side module, not a client side.
You can create a client that call an API coded on server side

**Comment by piyush2greedy** [comment]
@louis49 can u share any reference link on how to do it as need to create a local server in network. can u tell how to do it

**Comment by louis49** [comment]
You can find inspiration here : 
https://github.com/louis49/homebridge-plugin-androidtv/blob/main/homebridge/admin/api.js
