### ISSUE TITLE
How to send text

### ISSUE THREAD

**Issue by ghost** [louis49/androidtv-remote#32]
Does anyone have a clue how to send text to an Android TV?

I have decompiled an Android app and they seem to be using: ImeBatchEdit.

**Comment by louis49** [comment]
Interesting, I did'nt know about that. 
Look at this file : src/remote/remotemessage.proto you could find what objet to call with protobuf.
Don't hesitate to tell me if you find more infos about that because it can help to fix a bug when you show a text field on TV

**Comment by cd-dan** [comment]
This is the java of the decompiled proto: https://gist.github.com/cd-dan/6becd976a66f4155c69942792a73c77c
It seems that RemoteImeBatchEdit should contain a repeated EditInfo field?
(with additional info such as a string to send)

**Comment by cd-dan** [comment]
@louis49 I am stuck at this point, do you have some ideas?

**Comment by cd-dan** [comment]
Google Home app:
```
    public final void sendString(String str) {
        MessageProcessor messageProcessor2 = this.messageProcessor;
        GeneratedMessageLite.Builder createBuilder = ClientMessage.DEFAULT_INSTANCE.createBuilder();
        GeneratedMessageLite.Builder createBuilder2 = Ime$BatchEdit.DEFAULT_INSTANCE.createBuilder();
        GeneratedMessageLite.Builder createBuilder3 = Ime$Command.DEFAULT_INSTANCE.createBuilder();
        GeneratedMessageLite.Builder createBuilder4 = Ime$Command.ReplaceText.DEFAULT_INSTANCE.createBuilder();
        createBuilder4.copyOnWrite();
        Ime$Command.ReplaceText replaceText = (Ime$Command.ReplaceText) createBuilder4.instance;
        str.getClass();
        replaceText.bitField0_ |= 4;
        replaceText.text_ = str;
        createBuilder3.copyOnWrite();
        Ime$Command ime$Command = (Ime$Command) createBuilder3.instance;
        Ime$Command.ReplaceText replaceText2 = (Ime$Command.ReplaceText) createBuilder4.build();
        replaceText2.getClass();
        ime$Command.commandType_ = replaceText2;
        ime$Command.commandTypeCase_ = 2;
        createBuilder2.addCommand$ar$ds$ar$class_merging(createBuilder3);
        createBuilder.copyOnWrite();
        ClientMessage clientMessage = (ClientMessage) createBuilder.instance;
        Ime$BatchEdit ime$BatchEdit = (Ime$BatchEdit) createBuilder2.build();
        ime$BatchEdit.getClass();
        clientMessage.messageType_ = ime$BatchEdit;
        clientMessage.messageTypeCase_ = 21;
        messageProcessor2.sendMessage((ClientMessage) createBuilder.build());
    }
```

**Comment by cd-dan** [comment]
@louis49 Using your recommended https://braincoke.fr/blog/2021/03/android-reverse-engineering-for-beginners-decompiling-and-patching/#patching-with-apktool I was able to decompile an recompile an app using my own certificate. Do you have any clue how I can use the keystore in Wireshark to decrypt the TLS Application Data?

**Comment by nandishyb** [comment]
@ghost  were you able to get the payload for sending keyboard text? If so please provide the details.

**Comment by UniversalLab-Thang-Admin** [comment]
> @ghost were you able to get the payload for sending keyboard text? If so please provide the details.

hello did you solved sendText function?
