### ISSUE TITLE
Send text, analog adb command: "shell input text"

### ISSUE THREAD

**Issue by mirroringcontact** [louis49/androidtv-remote#35]
Hi. 
When keyboard on tv is shown i send letters one by one using adb.framework command "shell input text [char]". And it works. 
Now (with your framework) i'm trying 
androidRemote.sendKey(keyCode, RemoteDirection.SHORT); 
where keycodes for letters is: 
  A               = 29,
  B               = 30,
  C               = 31,
  D               = 32,
  E               = 33,
  F               = 34
  
 but  it doesn't work
  
Maybe you can add some functions for sending text?

**Comment by nandishyb** [comment]
@mirroringcontact I see you closed this issue. By any chance did you find a way to send the payload for sending keyboard Text to andriod Tv?

**Comment by starscodermoh** [comment]
@nandishyb did you find the protocols?
