### ISSUE TITLE
HI! Is it possible to integrate it with React Native?

### ISSUE THREAD

**Issue by MatanYamin** [louis49/androidtv-remote#42]

**Comment by freeboub** [comment]
No, not easily, there is another discussion with a swift port (if i remember well).
I personally tried to do it but my 'priority' changed and I never finished it. It is not plug and play as most of the dependencies of this package are not compatible with react native...
I let maintainers or other followers put additional comments.

**Comment by MatanYamin** [comment]
Thanks for the clarification!
