### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by piyush2greedy** [louis49/androidtv-remote#6]
@louis49 

Is there a way to replace protobufjs in react native as it gives error in loading .proto file. Is there any alternative for it

**Comment by louis49** [comment]
No. Event if you succeeded it, open a socket from a browser/react native is not possible.
You need to have a server that make calls to AndroidTV with ProtocolJS : your client can call this server to send it commands

**Comment by louis49** [comment]
Sorry, I made a mistake, it's really possible to ave a tcp tcp with react native. This plugin seems to do the job : https://github.com/Rapsssito/react-native-tcp-socket#ssl-client. 
You can fork my work and use this repo to replace the standard TCP Socket.
You need to understand that there is limitations of what you are doing : 
=> AndroidTV go to deep sleep when the remote is disconnected : then you will not power on it after coming back at home except manually
=> You can't have more that one network remote paired : if you pair a new one, the first one will be unpaired (the certificate will not be recognized)

**Comment by piyush2greedy** [comment]
Thanks for clarifying. Socket thing i will resolve.

Can u help in below point:
Is there a way to replace protobufjs in react native as it gives error in loading .proto file. Is there any alternative for it
