### ISSUE TITLE
save cert

### ISSUE THREAD

**Issue by Ganime422** [louis49/androidtv-remote#9]
hello

is there a way to save the cert afterthe first pairing and reuse later so I won't need to do the pairing process again?
I saw the method `getCertificate()` but it looks like it's used just to reconnect or something like that, it's not saving the cert into a .pem file.

thanks

**Comment by louis49** [comment]
Yes, you can use fs.writeFileSync (https://nodejs.org/api/fs.html) with cert and key. Save it by naming it cert.pem and key.pem

**Comment by Ganime422** [comment]
I'm trying to do something like:
```
    let cert = androidRemote.getCertificate();
    fs.writeFileSync("cert.pem", cert);
```
but since cert isn't in the correct format I'm getting this error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object`

to what format should I convert he cert then?
